#!/usr/bin/env bash
# build-brew-formula.sh — generate the Homebrew formula for a pinned release.
#
# Usage: bash scripts/build-brew-formula.sh <version> [checksums-file] [outdir]
#   <version>         vX.Y.Z or X.Y.Z (the pinned release tag)
#   [checksums-file]  default: dist/checksums.txt (scripts/build-release.sh output)
#   [outdir]          default: dist/
#
# Output: <outdir>/another-agent-skills.rb
#
# The formula points at the immutable release tarball (never a mutable branch),
# carries the sha256 from the release checksums, installs the framework tree
# into libexec, and symlinks bin/aas into bin so `aas` resolves its own tree
# (which contains scripts/lib/aas.sh).
#
# Asset naming is the single source of truth in scripts/lib/aas.sh
# (aas_asset_name): another-agent-skills-v<version>.tar.gz.
#
# Spec: PLAN.md — Phase 9 / P9.6

set -euo pipefail

REPO_SLUG="juandelossantos/another-agent-skills"
DESC="Skill-driven execution framework for AI coding agents"
LICENSE_NAME="MIT"

VERSION_ARG="${1:-}"
CHECKSUMS="${2:-dist/checksums.txt}"
OUTDIR="${3:-dist}"

if [ -z "$VERSION_ARG" ]; then
    echo "usage: bash scripts/build-brew-formula.sh <version> [checksums-file] [outdir]" >&2
    exit 2
fi

VERSION="${VERSION_ARG#v}"
case "$VERSION" in
    [0-9]*.[0-9]*.[0-9]*) : ;;
    *) echo "build-brew-formula: version must be vX.Y.Z (got '${VERSION_ARG}')" >&2; exit 2 ;;
esac

ASSET="another-agent-skills-v${VERSION}.tar.gz"
URL="https://github.com/${REPO_SLUG}/releases/download/v${VERSION}/${ASSET}"

if [ ! -f "$CHECKSUMS" ]; then
    echo "build-brew-formula: checksums file not found: ${CHECKSUMS}" >&2
    echo "  build the release first: bash scripts/build-release.sh v${VERSION} $(dirname "$CHECKSUMS")" >&2
    exit 1
fi

# Same entry lookup as scripts/lib/aas.sh (aas_verify_checksum): the release
# build writes `<hash>  <asset>` with the bare asset name.
SHA256="$(awk -v a="$ASSET" '$2==a || $2=="./"a {print $1; exit}' "$CHECKSUMS")"
if [ -z "$SHA256" ]; then
    echo "build-brew-formula: no checksum entry for ${ASSET} in ${CHECKSUMS} — refusing to generate a formula" >&2
    exit 1
fi

mkdir -p "$OUTDIR"
OUT="${OUTDIR%/}/another-agent-skills.rb"

cat > "$OUT" <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/build-brew-formula.sh — do not edit by hand.
# Source: https://github.com/${REPO_SLUG}
class AnotherAgentSkills < Formula
  desc "${DESC}"
  homepage "https://github.com/${REPO_SLUG}"
  url "${URL}"
  sha256 "${SHA256}"
  license "${LICENSE_NAME}"
  version "${VERSION}"

  def install
    # buildpath.children (not Dir["*"]) also carries dot-dirs the CLI needs,
    # e.g. .claude-plugin/ for guardrails.
    libexec.install buildpath.children
    bin.install_symlink libexec/"bin/aas"
  end

  test do
    system "#{bin}/aas", "--version"
  end
end
EOF

echo "built ${OUT}"
