#!/usr/bin/env bash
# stack-analysis.sh — Detect stack categories and recommend MCPs, skills, best practices
# Universal: works for ANY stack by detecting project CATEGORIES, not frameworks.

set -euo pipefail

REPO_ROOT=$(pwd)
STACK_CONFIG="${REPO_ROOT}/STACK_CONFIG.md"
OUTPUT="${REPO_ROOT}/STACK-ANALYSIS.md"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

detect_categories() {
  local cats=""
  [[ -f "package.json" ]] && grep -qE "react|vue|svelte|angular|next|nuxt|astro" package.json 2>/dev/null && cats="${cats}frontend,"
  [[ -f "package.json" ]] && grep -qE "react-native|expo|ionic" package.json 2>/dev/null && cats="${cats}mobile,"
  [[ -f "pubspec.yaml" ]] && grep -q "flutter" pubspec.yaml 2>/dev/null && cats="${cats}mobile,"
  [[ -f "package.json" ]] && grep -qE "tauri|electron" package.json 2>/dev/null && cats="${cats}desktop,"
  [[ -f "package.json" ]] && grep -qE "express|hono|fastify|nestjs|koa" package.json 2>/dev/null && cats="${cats}backend,"
  [[ -f "go.mod" ]] && cats="${cats}backend,"
  [[ -f "Cargo.toml" ]] && cats="${cats}backend,"
  [[ -f "pyproject.toml" ]] || [[ -f "requirements.txt" ]] && cats="${cats}backend,"
  [[ -f "Gemfile" ]] && cats="${cats}backend,"
  [[ -f "prisma/schema.prisma" ]] || [[ -f "drizzle.config.ts" ]] && cats="${cats}database,"
  [[ -f "package.json" ]] && grep -qE "prisma|drizzle|mongoose|sequelize|knex" package.json 2>/dev/null && cats="${cats}database,"
  [[ -f "package.json" ]] && grep -qE "jest|vitest|mocha|playwright|cypress" package.json 2>/dev/null && cats="${cats}testing,"
  [[ -f "pytest.ini" ]] || [[ -f "conftest.py" ]] && cats="${cats}testing,"
  echo "$cats" | sed "s/,$//" | tr "," "\n" | sort -u | tr "\n" "," | sed "s/,$//"
}

recommend_mcps() {
  local cats="$1"
  echo "## Recommended MCPs"
  echo ""
  echo "| MCP | What it does | Token cost | When to use |"
  echo "|---|---|---|---|"
  echo "| Context7 | Live library docs, prevents hallucinated APIs | Low (1k-5k/query) | Any project with dependencies |"
  echo "| GitHub MCP | PRs, issues, Actions, repo operations | Medium | Any project with git |"
  echo "$cats" | grep -q "frontend\|mobile\|desktop" && echo "| Playwright MCP | Browser automation, E2E testing | Medium | Any web/UI project |"
  echo "$cats" | grep -q "database" && echo "| Database MCP | Schema inspection, queries, migrations | Medium-High | Projects with databases |"
  echo "$cats" | grep -q "frontend\|mobile" && echo "| Figma MCP | Design-to-code, design tokens | High | Projects with Figma designs |"
  echo ""
  echo "> MCPs consume tokens. Start with Context7 + GitHub MCP. Add others only when needed."
}

recommend_skills() {
  local cats="$1"
  echo "## Applicable Skills"
  echo ""
  echo "### Any project"
  echo "- spec-driven-development, git-init-and-versioning, project-health-check"
  echo ""
  echo "$cats" | grep -q "frontend" && echo -e "### Frontend\n- frontend-web, visual-frontend-mastery, frontend-ui-engineering\n"
  echo "$cats" | grep -q "mobile" && echo -e "### Mobile\n- frontend-mobile\n"
  echo "$cats" | grep -q "backend" && echo -e "### Backend\n- backend-api-mastery, security-and-hardening\n"
  echo "$cats" | grep -q "testing" && echo -e "### Testing\n- test-driven-development, debugging-and-error-recovery\n"
  echo "### Quality"
  echo "- code-review-and-quality, planning-and-task-breakdown, architecture-analysis"
}

recommend_practices() {
  echo "## Best Practices"
  echo ""
  echo "- Use STACK_CONFIG.md commands for test/lint/build"
  echo "- Follow Rule 9: Verification checklist before marking complete"
  echo "- Use .env + .gitignore for secrets (never hardcode)"
  echo "- Document design decisions in DESIGN.md for UI work"
}

main() {
  echo ""
  echo "=== STACK ANALYSIS ==="
  echo ""

  [[ ! -f "$STACK_CONFIG" ]] && echo -e "${YELLOW}No STACK_CONFIG.md found. Run init-agents first.${NC}" && exit 1

  local cats
  cats=$(detect_categories)
  [[ -z "$cats" ]] && cats="general"

  echo -e "${GREEN}Detected:${NC} ${cats}"
  echo ""

  cat > "$OUTPUT" << EOF
# Stack Analysis

**Generated by:** stack-analysis.sh (another-agent-skills)
**Categories:** ${cats}
**Stack config:** STACK_CONFIG.md

$(recommend_mcps "$cats")

$(recommend_skills "$cats")

$(recommend_practices)
EOF

  echo -e "${GREEN}Created:${NC} STACK-ANALYSIS.md"
}

main "$@"
